Add logic to handle and send 404 for unregistered routes and send pro…
Chirag-And-Dheeraj/video-streaming-server pull request #20
Opened 2024-05-11 16:31 UTC by chiraglulla

…per error codes from server to client

2024-05-25 11:22 UTC, dheerajdlalwani requested changes
We have some fixes to look at.

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		http.Error(w, "Error Retreiving Records", http.StatusInternalServerError)
```suggestion
		http.Error(w, "Error retreiving videos", http.StatusInternalServerError)
```

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +			http.Error(w, "Error Processing File", http.StatusInternalServerError)
```suggestion
			http.Error(w, "Error processing file", http.StatusInternalServerError)
```

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +			http.Error(w, "Error Retreiving Records", http.StatusInternalServerError)
```suggestion
			http.Error(w, "Error retreiving videos", http.StatusInternalServerError)
```

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		http.Error(w, "Error Retreiving Records", http.StatusInternalServerError)
```suggestion
		http.Error(w, "Error retreiving videos", http.StatusInternalServerError)
```

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		return
What happens when no rows are returned?
In case of no rows, return a 404 not found.

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		http.Error(w, "Error Retreiving Record", http.StatusInternalServerError)
```suggestion
		http.Error(w, "Error retrieving video", http.StatusInternalServerError)
```

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		http.Error(w, "Error Retreiving Video", http.StatusInternalServerError)
```suggestion
		http.Error(w, "Error retrieving video", http.StatusInternalServerError)
```

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		http.Error(w, "Error Retreiving Video", http.StatusInternalServerError)
Also, if requested manifest file does not exist, return a 404

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		http.Error(w, "Error Retreiving Video", http.StatusInternalServerError)
```suggestion
		http.Error(w, "Error retrieving video", http.StatusInternalServerError)
```

2024-05-25 11:22 UTC, dheerajdlalwani commented on controllers/video.go
> +		http.Error(w, "Error Retreiving Video", http.StatusInternalServerError)
```suggestion
		http.Error(w, "Error retrieving video", http.StatusInternalServerError)
```

2024-06-09 16:21 UTC, dheerajdlalwani commented
What's the progress here, @chiraglulla ?

2024-07-13 15:36 UTC, dheerajdlalwani requested changes

2024-07-13 15:43 UTC, chiraglulla commented on .vscode/settings.json
It was already resolved in other branch and merged to main. As you can't see it in main now.

2024-07-13 15:44 UTC, chiraglulla commented on client/upload.html
> +          <input id="thumbnail" type="file" name="thumbnail" accept="image/*" /> -->
Done.

2024-07-13 16:13 UTC, closed without merging

2024-07-13 16:14 UTC, chiraglulla commented on .vscode/settings.json
Removed.